#!/bin/bash
#Pre-install script

#/opt/apps/issue-gen/issuegen-stop.sh

sleep 180s
#cd /opt/apps/issue-gen
proc=`ps -ef|grep issuegen |grep -v grep |awk '{ print $2}'`
if [ -z "$proc" ]; then
   echo "App is not running. Proceeding with installation ..."
else
   echo "App is running. Stopping it before installation ..."
   kill -9 $proc
   DTSTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
   export LOG_FILE="issuegen.log"
   cd /opt/apps/issue-gen
   cp -v $LOG_FILE $LOG_FILE_$DTSTAMP.log
fi

