#!/bin/bash
#Pre-install script

#/opt/apps/issue-gen/issuegen-stop.sh

sleep 180s
#cd /opt/apps/issue-gen
proc=`ps -ef|grep issuegen |grep -v grep |awk '{ print $2}'`
if [ -z "$proc" ]; then
   echo "App is not running. Proceeding with installation ..."
else
   echo "App is running. Stopping it before installation ..."
   kill -9 $proc
fi

#touch nohup.out
