name: "Create Code Reivew PR1"

on:
  push:
    branches:
      - '*abvv'
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g
  CONTAINER_REGISTRY: quay.io/opsmxpublic
  
jobs:
  test-workflow-1-in-local-repotest:
    uses: yugaa22/world-hello/.github/workflows/one.yml@master
