# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
  CONTAINER_REGISTRY: quay.io/opsmxpublic

jobs:
  gradle-igor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpsMx Igor repo
      uses: actions/checkout@v3
      with:
        repository: opsmx/igor
        ref: refs/heads/v4.7.3-1.28.4
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - run: echo "💡 The OpsMx/igor repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: List files in the repository and the branch 
      run: |
          ls ${{ github.workspace }} 
          echo "Dockerfile"
          ls -ltra docker/ubi8
          echo "Igor Git Branch"
          git branch 
    - name: Prepare build variables
      id: build_variables
      run: |
          echo ::set-output name=REPO::igor
          echo ::set-output name=VERSION::v1
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: release-candidate
    - run: ./gradlew build #--dry-run
    - name: List files in the repository and the branch 
      run: |
          ls ${{ github.workspace }} 
          echo "Dockerfile"
          ls -ltra docker/ubi8
          echo "Igor Git Branch"
          git branch 
          
          docker build -f docker/ubi8/Dockerfile-fips -t quay.io/opsmxpublic/igor:testv1 .
